#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "gruvbox"
    background = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    filemanager = "nerdtree"
    sidebar_direction = 'right'
    tabstop = 4
    expandtab = true
    shiftwidth = 4
    bootstrap_after = "configs#after"
    max_column = 123

[[custom_plugins]]
    name = 'joshdick/onedark.vim'
    merged = 0

[[custom_plugins]]
    name = 'mg979/vim-visual-multi'
    merged = 0

[[custom_plugins]]
    name = "ryanoasis/vim-devicons"
    merged = 0

[[custom_plugins]]
    name = "tiagofumo/vim-nerdtree-syntax-highlight"
    merged = 0

[[custom_plugins]]
    name = "sebdah/vim-delve"
    merged = 0

[[custom_plugins]]
    name = "buoto/gotests-vim"
    merged = 0

[[custom_plugins]]
    name = "prettier/vim-prettier"
    merged = 0

[[custom_plugins]]
    name = "mileszs/ack.vim"
    merged = 0

[[custom_plugins]]
    name = "nsf/gocode"
    merged = 0

[[custom_plugins]]
    name = "samoshkin/vim-mergetool"
    merged = 0

[[custom_plugins]]
    name = "airblade/vim-gitgutter"
    merged = 0

[[custom_plugins]]
    name = "tpope/vim-fugitive"
    merged = 0

# [[custom_plugins]]
#    name = 'vim-airline/vim-airline'

#[[custom_plugins]]
#    name = 'vim-airline/vim-airline-themes'

# ---- LAYERS ----

[[layers]]
    name = "gtags"

[[layers]]
    name = "VersionControl"

[[layers]]
    name = 'checkers'
    lint_on_the_fly = true

# [[layers]]
#    name = 'debug'

[[layers]]
    name = 'default'

[[layers]]
    name = 'fzf'

[[layers]]
    name = 'git'

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 20

[[layers]]
    name = 'lang#dockerfile'

# [[layers]]
#    name = 'lang#graphql'

# [[layers]]
#    name = 'lang#ruby'

# [[layers]]
#    name = 'lang#vue'

[[layers]]
    name = 'lang#markdown'

[[layers]]
    name = 'lang#elixir'

[[layers]]
    name = 'lang#go'

[[layers]]
    name = 'lang#python'
    enable_typeinfo = true

# [[layers]]
#    name = 'lang#javascript'

[[layers]]
    name = 'lang#toml'

[[layers]]
    name = 'lang#html'

[[layers]]
    name = 'lang#sh'
