#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "onedark"
    background = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    filemanager = "nerdtree"
    sidebar_direction = 'left'
    tabstop = 4
    expandtab = true
    shiftwidth = 4
    bootstrap_after = "configs#after"
    max_column = 123

[[custom_plugins]]
    name = 'joshdick/onedark.vim'

[[custom_plugins]]
    name = "ryanoasis/vim-devicons"

[[custom_plugins]]
    name = "rking/ag.vim"

[[custom_plugins]]
    name = "tiagofumo/vim-nerdtree-syntax-highlight"

[[custom_plugins]]
    name = "sebdah/vim-delve"

[[custom_plugins]]
    name = "buoto/gotests-vim"

[[custom_plugins]]
    name = "prettier/vim-prettier"

# [[custom_plugins]]
#    name = 'vim-airline/vim-airline'

#[[custom_plugins]]
#    name = 'vim-airline/vim-airline-themes'

[[layers]]
  name = "VersionControl"

# [[layers]]
#     name = 'core#statusline'
#     enable = true
 
# [[layers]]
#     name = 'core#tabline'
#     enable = false

[[layers]]
    name = 'checkers'
    lint_on_the_fly = true

[[layers]]
    name = 'debug'

[[layers]]
    name = 'default'

[[layers]]
    name = 'fzf'

[[layers]]
    name = 'git'

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 20

[[layers]]
    name = 'lang#dockerfile'

[[layers]]
    name = 'lang#graphql'

[[layers]]
    name = 'lang#ruby'

[[layers]]
    name = 'lang#vue'

[[layers]]
    name = 'lang#markdown'

[[layers]]
    name = 'lang#elixir'

[[layers]]
    name = 'lang#go'

[[layers]]
    name = 'lang#python'

[[layers]]
    name = 'lang#javascript'

[[layers]]
    name = 'lang#toml'

[[layers]]
    name = 'lang#html'

[[layers]]
    name = 'lang#sh'
